- name: latest version of all required packages installed
  hosts: all
  become: yes
  remote_user: "akshay"
  tasks:

    - name: install redis on Debian based distros
      apt:
        name: apache2
        state: present
      become: true
      notify: start apache2
      when: ansible_os_family == 'Debian'

    - name: install redis on RHEL based distros
      yum:
        name: "{{ item }}"
        state: present
        update_cache: true
      become: true
      loop:
        - httpd
      notify: start httpd
      when: ansible_os_family == 'RedHat'

  handlers:
    - name: start httpd
      service:
        name: httpd
        state: started
        enabled: true
      ignore_errors: yes
    - name: start apache2
      service:
        name: apache2
        state: started
        enabled: true
      ignore_errors: yes
